
   
title: <br>Developmental Coupling Of Cerebral Blood Flow and fMRI Fluctuations In Youth
logo: https://github.com/PennLINC/IntermodalCoupling/blob/gh-pages2/CR_revision/Full_figures/Intro_figure.png
description: <br>
theme: jekyll-theme-minimal
